In [1]:
import gym
import torch

In [2]:
env = gym.make('CarRacing-v0')

In [3]:
from parameters.architectures_torch import Nature_Paper_Conv_Dropout_Torch

In [80]:
X = torch.rand(32,4,96,96)
X.shape

torch.Size([32, 4, 96, 96])

In [76]:
net = Nature_Paper_Conv_Dropout_Torch(4, 5)

In [81]:
net(X).shape

torch.Size([32, 5])

In [82]:
net._get_dense_input_neurons(4, (96,96))

9216

In [7]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

In [8]:
DEVICE

'cpu'

In [9]:
a = torch.nn.Linear(10,10)
b = torch.nn.Linear(10,10)

In [17]:
a.weight == b.weight

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [12]:
b.load_state_dict(a.state_dict())

<All keys matched successfully>

In [16]:
a.weight.data += 1

In [33]:
torch.eye(5)[torch.arange(32)%5].argmax(dim=1,keepdim=True).shape

torch.Size([32, 1])

In [36]:
torch.tensor([True],dtype=torch.float32)

tensor([1.])

In [43]:
torch.eye(5).unsqueeze(0).shape#.gather(1, torch.tensor([4]))

torch.Size([1, 5, 5])

In [46]:
X = torch.rand(32,5)
X.gather(1, (torch.arange(32)%5).unsqueeze(0))

tensor([[0.3962, 0.9645, 0.5881, 0.1742, 0.1580, 0.3962, 0.9645, 0.5881, 0.1742,
         0.1580, 0.3962, 0.9645, 0.5881, 0.1742, 0.1580, 0.3962, 0.9645, 0.5881,
         0.1742, 0.1580, 0.3962, 0.9645, 0.5881, 0.1742, 0.1580, 0.3962, 0.9645,
         0.5881, 0.1742, 0.1580, 0.3962, 0.9645]])

In [49]:
(torch.rand(32,1) + (1 - torch.rand(32,1)) * torch.rand(32,5)).shape

torch.Size([32, 5])

In [63]:
torch.rand(5).tile(32,1).shape

torch.Size([32, 5])

In [64]:
torch.arange(5).unsqueeze(1)

torch.Size([5, 1])

In [74]:
X.amax(dim=1).mean().item()

0.846293032169342